Add Cloud foundry manifest
Two issues:

1. High availability
2. Postgres client connectivity

1. High availability

Currently not possible to run multiple instances of this app.  The app
will start, but Javascript console shows connections to
wss://app-domain/socket.io/ are failing.  Presumably, the app is
stateful in some way. Example of the full error (secrets no longer
relevant):

```
Error: "xhr poll error"
onErrorhttps://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js:2:7328doPollhttps://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js:2:1979emithttps://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js:1:12370onErrorhttps://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js:2:3683onreadystatechangehttps://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js:2:3309 3.index.8e11967f017261b5c7b5.js:57463:4

Firefox can't establish a connection to the server at wss://paas-hackmd.henry.dev.cloudpipelineapps.digital/socket.io/?noteId=J0s7FWPWRliPtC7wZy6E6Q&EIO=3&transport=websocket&sid=2HXaCVYnYSszMDM4AAAF. websocket.js:112

Source map error: request failed with status 404
Resource URL: https://paas-hackmd.henry.dev.cloudpipelineapps.digital/build/3.index.8e11967f017261b5c7b5.js
Source Map URL: sequence-diagram-min.js.map[Learn More]
```

I thought it was the absence of a configured session secret, because
a random one gets generated if you don't specify one. However, setting
`CMD_SESSION_SECRET` in the environment produced the same results.

2. Postgres client connectivity

I set `PGSSLMODE` to `require` because otherwise the app logs an error
about failing to connect. The error message ended in `SSL OFF`. The
quick fix is to add this environment variable. A better long-term fix
would be to use a sensibly configured client.

Signed-off-by: Lee Porte <lee.porte@digital.cabinet-office.gov.uk>